### ISSUE TITLE
Warehouse with Chart Subscription to a HTTP-only OCI registry fails to discover charts

### ISSUE THREAD

**Issue by ndriessen** [akuity/kargo#4783]
Configure a warehouse with a chart subscription, that points to an OCI registry.
The OCI registry is running locally in-cluster and only supports HTTP.
```
spec:
  freightCreationPolicy: Automatic
  interval: 1m0s
  subscriptions:
    - image:
        discoveryLimit: 5
        imageSelectionStrategy: SemVer
        insecureSkipTLSVerify: true
        repoURL: oci-registry.oci-registry.svc.cluster.local/invoicing
        semverConstraint: ">=0.0.1"
        strictSemvers: true
    - chart:
        discoveryLimit: 5
        repoURL: oci://oci-registry.oci-registry.svc.cluster.local/helm/invoicing
        semverConstraint: ">=0.0.1"
```
The image discovery works, but the chart discovery fails with:
```
 error retrieving versions of chart from repository \"oci://oci-registry.oci-registry.svc.cluster.local/helm/planning\": Get \"https://oci-registry.oci-registry.svc.cluster.local/v2/helm/planning/tags/list\": dial tcp 10.96.120.140:443: i/o timeout" namespace=team2 warehouse=planning-warehouse
time="2025-08-07T09:34:02Z" level=error msg="Reconciler error" Warehouse="{planning-warehouse team2}" controller=warehouse controllerGroup=kargo.akuity.io controllerKind=Warehouse error="error discovering artifacts: error discovering charts: error discovering chart versions from helm chart repo \"oci://oci-registry.oci-registry.svc.cluster.local/helm/planning\": error retrieving versions of chart from repository \"oci://oci-registry.oci-registry.svc.cluster.local/helm/planning\": Get \"https://oci-registry.oci-registry.svc.cluster.local/v2/helm/planning/tags/list\": dial tcp 10.96.120.140:443: i/o timeout" name=planning-warehouse namespace=team2 reconcileID="\"dd467ea0-900c-4f1c-be1e-7b364c6615a0\""
```

# Version
1.7.1

**Comment by ndriessen** [comment]
using a promotion step with oci-download does work, it seems the promotion step uses helm/registry.go, while the warehouse uses chart.OciSelector. 
The Registry implementation has explicit support to fallback to HTTP if HTTPS is not available, the OciSelector has not. So it only tries to connect using HTTPS

**Comment by krancour** [comment]
I've not dug too deep, but I know the OCI download step being very new is using a better, more modern library for OCI registry interactions than is the selector. The selector code was recently _structurally_ refactored, but all the original logic and underlying stack remain unchanged.

@hiddeco I think you've had your eye on getting right of oras for a while. And I think we nearly have. Is fixing this impetus for finishing that off?

**Comment by hiddeco** [comment]
This comes from Helm switching from ORAS v1 to v2, which no longer has the HTTPS -> HTTP fallback built-in. As we still use ORAS for everything Helm-related (to piggyback on certain functionalities from upstream), this also applies to the (Helm) OCI selector. We forgot, however, to apply the fallback transport there as is being done upstream (and as we are doing elsewhere).

This should be solved with #4832.

**Comment by ndriessen** [comment]
@hiddeco It seems this did not fix the issue unfortunately

I updated Kargo to 1.7.4 and retried the setup, but it still fails to discover charts from a HTTP OCI registry:

`Unable to discover artifacts: error discovering charts: error discovering chart versions from helm chart repo "oci://oci-registry.oci-registry.svc.cluster.local/helm/invoicing": error retrieving versions of chart from repository "oci://oci-registry.oci-registry.svc.cluster.local/helm/invoicing": Get "https://oci-registry.oci-registry.svc.cluster.local/v2/helm/invoicing/tags/list": dial tcp 10.96.94.179:443: i/o timeout`

I think the issue might be with the error check in the fallback transport, it checks on `tls.RecordHeaderError`

https://github.com/akuity/kargo/blob/eefbfe72e2b0e9b4b49f51c23c60b7acd94d0894/internal/helm/registry.go#L128


but looking at the go code for http.Client, it seems to already catch the `tls.RecordHeaderError` error and return `ErrSchemeMismatch` instead, which potentially does not cause the fallback transport to trigger?

https://cs.opensource.google/go/go/+/refs/tags/go1.25.0:src/net/http/client.go;drc=4d1c255f159d90557b43ede07f8b9a209e1fb49c;l=265

**Comment by hiddeco** [comment]
I have been trying to replicate this using a Harbor registry with HTTP only enabled, and failed to reproduce this.

However, this replication slightly differs from your attempt, as the registry is hosted at a specific port (`:5000`). Given this, can you try the following to see if that yields a different result?

```yaml
spec:
  freightCreationPolicy: Automatic
  interval: 1m0s
  subscriptions:
    - image:
        discoveryLimit: 5
        imageSelectionStrategy: SemVer
        insecureSkipTLSVerify: true
        repoURL: oci-registry.oci-registry.svc.cluster.local/invoicing
        semverConstraint: ">=0.0.1"
        strictSemvers: true
    - chart:
        discoveryLimit: 5
        repoURL: oci://oci-registry.oci-registry.svc.cluster.local:80/helm/invoicing
        semverConstraint: ">=0.0.1"
```

**Comment by ndriessen** [comment]
@hiddeco That seems indeed to do the trick, adding the port 80 explicitly solved it. Might be good to add something to the documentation concerning this, as it is not something you would automatically think of when using standard ports....

Thanks for helping pinpoint the issue and the solution!
